In [7]:
from sklearn.linear_model import LinearRegression
import numpy as np

In [9]:
m = np.array([[50], [90], [120], [180]])
s = np.array([10.000, 45.000, 90.000, 130.000])

In [26]:
m

array([[ 50],
       [ 90],
       [120],
       [180]])

In [11]:
model = LinearRegression()

In [12]:
model.fit(m,s)

LinearRegression()

In [16]:
model.predict([[100]])

array([59.30555556])

In [20]:
y = np.array([[2020], [2021], [2022], [2023], [2024], [2025]])
p = np.array([10, 12, 15, 19, 21, 25])

In [27]:
mf

array([[2020],
       [2021],
       [2022],
       [2023],
       [2024],
       [2025]])

In [22]:
model = LinearRegression()

In [23]:
model.fit(y,p)

LinearRegression()

In [30]:
model.predict([[2026]])

array([27.6])

In [31]:
import pandas as pd

In [37]:
from sklearn.model_selection import train_test_split

In [69]:
data = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Advertising.csv')

In [70]:
x = data[['TV', 'radio', 'newspaper']]
y = data['sales']

In [71]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [72]:
model = LinearRegression()

In [73]:
model.fit(x_train, y_train)

LinearRegression()

In [74]:
model.predict(x_test[:5])

array([16.4080242 , 20.88988209, 21.55384318, 10.60850256, 22.11237326])

In [75]:
data = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')

In [76]:
data.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [77]:
x = data[['age', 'rm']]
y = data['medv'] 

In [78]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 30)

In [79]:
model = LinearRegression()

In [80]:
model.fit(x_train, y_train)

LinearRegression()

In [82]:
model.predict(x_test[:2])

array([18.23193603, 16.74357725])

In [83]:
x_test

age     rm
21    89.2  5.965
440   92.4  5.818
103   87.4  6.137
178   74.4  6.860
22    91.7  6.142
..     ...    ...
3     45.8  6.998
323   74.3  5.708
41     2.9  6.770
208   59.1  6.064
442  100.0  6.219

[102 rows x 2 columns]

In [84]:
from sklearn.linear_model import LogisticRegression

In [85]:
x = np.array([[40], [50], [20], [90]])
y = np.array([0, 1, 0, 1])

In [86]:
model = LogisticRegression()

In [87]:
model.fit(x, y)

LogisticRegression()

In [88]:
model.predict([[30]])

array([0])

In [89]:
model.predict([[50]])

array([1])

In [91]:
x = np.array([[20], [45], [30], [60], [55], [35], [70], [15], [5], [90]])
y = np.array([0, 0, 0, 1, 1, 0, 1, 0, 0, 1])

In [92]:
model = LogisticRegression()

In [93]:
model.fit(x, y)

LogisticRegression()

In [94]:
model.predict([[25]])

array([0])

In [95]:
model.predict([[80]])

array([1])

In [97]:
data = pd.read_csv('https://raw.githubusercontent.com/sam16tyagi/Machine-Learning-techniques-in-python/master/logistic%20regression%20dataset-Social_Network_Ads.csv')

In [99]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [121]:
from sklearn.metrics import (confusion_matrix, accuracy_score, f1_score)

In [122]:
x = data[['EstimatedSalary', 'Age']]
y = data['Purchased']

In [123]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 50)

In [124]:
model = LogisticRegression()

In [125]:
model.fit(x_train, y_train)

LogisticRegression()

In [133]:
y_pred = model.predict(x_test)

In [134]:
y_pred

array([0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [135]:
confusion_matrix(y_pred, y_test)

array([[52, 11],
       [ 2, 15]], dtype=int64)

In [136]:
accuracy_score(y_pred, y_test)

0.8375

In [137]:
f1_score(y_pred, y_test)

0.6976744186046512